<a href="https://colab.research.google.com/github/Charan-Gond/Blue-Bus/blob/main/00_introduction_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

get dhadg

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
# creating tesor
scallar =tf.constant(7)
scallar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# dimention of tensor ndim->number of dimention
scallar.ndim

0

In [ ]:
# vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# creating changable tensor
cha_tensor=tf.Variable([10,7])
uncha_tensor=tf.constant([10,7])
cha_tensor,uncha_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#changing value
cha_tensor[0].assign(7)
cha_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# random tensor
random1=tf.random.Generator.from_seed(18)
random1=random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.35877243, -1.9095894 ],
       [-0.2094769 ,  0.8286217 ],
       [-0.06695071, -0.35105535]], dtype=float32)>

In [ ]:
# shuffling
un_shuffled=tf.constant([[3,1],[5,8],[9,0]])
tf.random.set_seed(42)
tf.random.shuffle(un_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 8],
       [9, 0],
       [3, 1]], dtype=int32)>

In [ ]:
tf.ones()

TypeError: Missing required positional argument

In [ ]:
x=tf.constant([[10,7],[4,3]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  3]], dtype=int32)>

In [ ]:
y=x[...,tf.newaxis]
y

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 3]]], dtype=int32)>

In [ ]:
tensor_rank2=tf.constant([[3,10],[9,8]])
rank_3=tf.expand_dims(tensor_rank2,axis=2)
tensor_rank2,rank_3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3, 10],
        [ 9,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[ 3],
         [10]],
 
        [[ 9],
         [ 8]]], dtype=int32)>)

In [ ]:
f=tf.cast(x,tf.float16)
x,f

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 4,  3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 4.,  3.]], dtype=float16)>)

In [ ]:
# tf.reduce_variance(x)
data = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
x,tf.math.reduce_std(tf.cast(x,dtype=tf.float32))
# tf.reduce_min(x)

InvalidArgumentError: {{function_node __wrapped__Mean_device_/job:localhost/replica:0/task:0/device:CPU:0}} Invalid reduction dimension (2 for input with 2 dimension(s) [Op:Mean] name: 

indices=[1,3,5]
tf.one_hot(indices,depth=4)

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Apr 13 12:46:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----